site_name: Hack-the-Planet
site_url: https://eaton-lab.org/hack-the-planet
repo_url: https://github.com/eaton-lab/hack-the-planet
edit_uri: edit/master/docs/

theme:
  name: material
  highlightjs: true
  palette:
    - scheme: default
      primary: blue
      ascent: indigo
      toggle: 
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      ascent: indigo
      toggle: 
        icon: material/lightbulb
        name: Switch to lightmode
  favicon: /images/favicon.ico
  icon:
    logo: material/hexagon-multiple-outline
  features:
    - navigation.instant     # revisit this if reloading is not great...
    - navigation.tracking
    - search.highlight    # - navigation.indexes
    - search.suggest
    - content.code.annotate # 
    - content.code.copy
    # - toc.follow    
    # - navigation.expand    
    # - navigation.sections
    # - navigation.tabs      

extra_javascript:

extra_css:
  - stylesheets/pages.css
  # - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/styles/monokai.min.css  
  # - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/styles/monokai-sublime.min.css
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/styles/base16-unikitty-light.min.css  

extra_javascript:
  # - javascripts/extra.js
  # - javascripts/mathjax.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/highlight.min.js  
  # - https://polyfill.io/v3/polyfill.min.js?features=es6
  # - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js  

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - tables
  - md_in_html
  - pymdownx.details  
  - pymdownx.superfences
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg      
  # - pymdownx.highlight:
  #     use_pygments: true
  #     pygments_lang_class: true

nav: 
  - About: index.md
  - Syllabus: pages/syllabus
  - Schedule: pages/schedule
  - Sessions: 
    - Session 1 - (1/21): sessions/session-1
    - Session 2 - (1/23): sessions/session-2
    - Session 3 - (1/28): sessions/session-3
    - Session 4 - (1/30): sessions/session-4.md
    - Session 5 - (2/4): sessions/session-5.md
    - Session 6 - (2/6): sessions/session-6.md
    - Session 7 - (2/11): sessions/session-7.md
    - Session 8 - (2/13): sessions/session-8.md
    - Session 9 - (2/18): sessions/session-9.md
    - Session 10 - (2/20): sessions/session-10.md
    - Session 11 - (2/25): sessions/session-11.md
    - Session 12 - (2/27): sessions/session-12.md
    - Session 13 - (3/4): sessions/session-13.md
    - Session 14 - (3/6): sessions/session-14.md
    - Session 15 - (3/11): sessions/session-15.md
    - Session 16 - (3/13): sessions/session-16.md
    - Session 17 - (3/25): sessions/session-17.md
    - Session 18 - (3/27): sessions/session-18.md
    - Session 19 - (4/1): sessions/session-19.md
    - Session 20 - (4/3): sessions/session-20.md
    - Session 21 - (4/8): sessions/session-21.md
    - Session 22 - (4/10): sessions/session-22.md
    - Session 23 - (4/15): sessions/session-23.md
    - Session 24 - (4/17): sessions/session-24.md
    - Session 25 - (4/22): sessions/session-25.md
    - Session 26 - (4/24): sessions/session-26.md
    - Session 27 - (4/29): sessions/session-27.md

  - Tutorials:
    - Session 2 - (1/23):
        - 2.0 -- GitHub: tutorials/2.0-github
        - 2.1 -- Shell: tutorials/2.1-shell
        - 2.2 -- Shell challenge: tutorials/2.2-bash
    - Session 3 - (1/28):
        - 3.1 -- Markdown: tutorials/3.1-markdown
        - 3.2 -- git branching: tutorials/3.2-git-branching
        - 3.3 -- GitHub pages: tutorials/3.3-github-pages
    - Session 4 - (1/30):
        - 4.0 -- conda: tutorials/4.0-conda
        - 4.1 -- jupyter: tutorials/4.1-jupyter
        - 4.2 -- GitHub fork: tutorials/4.2-forking
    - Session 5 - (2/4):
        - 5.0 -- Python variables, lists, loops: tutorials/5.0-python-part1
    - Session 6 - (2/6):
        - 6.0 -- Python (dict, if/else, functions): tutorials/6.0-python-part2
        - 6.1 -- Wright-Fisher model miniproject: tutorials/6.1-microproject-wf
    - Session 7 - (2/11):
        - 7.0 -- Subprocess: tutorials/7.0-subprocess
        - 7.1 -- Think-functionally: tutorials/7.1-think
        - 7.2 -- Scripting: tutorials/7.2-scripting
        - 7.3 -- Imports: tutorials/7.3-imports
    - Session 8 - (2/13):
        - 8.0 -- Classes: tutorials/8.0-wf-class
        - 8.1 -- Data Science: tutorials/8.1-data-science
    - Session 9 - (2/18):
        - 9.0 -- Scripting basics: tutorials/9.0-scripting.md
        - 9.1 -- Scripting the WF model: tutorials/9.1-wf-script.md
    - Session 10 - (2/20):
        - 10.0 -- Sublime text: tutorials/10.0-sublimetext3.md
        - 10.1 -- Style: tutorials/10.1-style.md
    - Session 11 - (2/25):
        - 11.0 -- Mini-project kickoff: tutorials/11.0-miniproject-kickoff.md
    - Session 12 - (2/27):
        - 12.0 -- REST APIs for Bio Data: tutorials/12.0-api-access.md
        - 12.1 -- VCF Files: tutorials/12.1-vcf-files.md
    - Session 13 - (3/4):
        - 13.0 -- Debugging Challenges: tutorials/13.0-DebuggingChallenges.md
    - Session 14 - (3/6):
        - 14.0 -- Debugging Challenges 2: tutorials/14.0-DebuggingChallenges2.md
        - 14.1 -- Data Visualization: tutorials/14.1-intro-plotting.md
    - Session 15 - (3/11):
        - 15.0 -- Debugging Challenges 3: tutorials/15.0-DebuggingChallenge3.md
        - 15.1 -- Machine Learning: tutorials/15.1-intro-scikit.md
    - Session 17 - (3/25):
        - 17.0 -- Git Collab: tutorials/17.0-git-collab.md
        - 17.1 -- Git Conflicts: tutorials/17.1-git-conflict.md
        - 17.2 -- Git In Class: tutorials/17.2-git-in-class.md
        # - 17.1 -- Debugging Challenge 4: ...
        # - 17.2 -- GitHub-advanced: ...
    - Session 18 - (3/27):
        - 18.1 -- Paired Program: tutorials/18.1-git-collab-assign.md
    - Session 20 -- (4/3):
        - 20.0 -- Dashboards for Data Science: tutorials/20.0-easy-webapps.md
    - Session 22 -- (4/10):
        - 22.0 -- Python time series analysis: tutorials/22.0-timeseries.md
    - Session 24 -- (4/17):
        - 24.0 -- Intro to HPC Systems: tutorials/24.0-intro-hpc.md    
    - Session 26 -- (4/24):
       - 26.0 -- Intro to Geospatial Analysis: tutorials/26.0-intro-gis.md

  - Resources:
    - project proposals: pages/proposals
    - project presentations: pages/presentations
    - project submissions: pages/project-submit
    - pinky server: https://pinky.eaton-lab.org/
    - repos: data/usernames.csv
  - External Links: 
    - courseworks: https://courseworks2.columbia.edu/courses/sis_course_id:EEEBW4050_001_2025_1
    - gitter chatroom: https://gitter.im/hack-the-planet-course/community
